// Shared: leave type defaults + accrual templates
export const LEAVE_TYPE_DEFAULTS = [
  {
    name: 'Yıllık İzin',
    code: 'ANNUAL',
    color: '#3B82F6',
    icon: '🏖️',
    accrualMethod: 'STANDARD',
    defaultDaysPerYear: 14,
    requiresApproval: true,
    requiresDocument: false,
    minDaysNotice: 7,
    maxConsecutiveDays: 0,
    canCarryOver: true,
    carryOverDays: 14,
    isPaid: true,
    sortOrder: 1,
  },
  {
    name: 'Haftalık İzin',
    code: 'WEEKLY',
    color: '#10B981',
    icon: '📅',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: false,
    requiresDocument: false,
    minDaysNotice: 0,
    maxConsecutiveDays: 1,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 2,
  },
  {
    name: 'Hastalık İzni',
    code: 'SICK',
    color: '#EF4444',
    icon: '🏥',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: true,
    minDaysNotice: 0,
    maxConsecutiveDays: 0,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 3,
  },
  {
    name: 'Doğum İzni',
    code: 'MATERNITY',
    color: '#EC4899',
    icon: '🤱',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: true,
    minDaysNotice: 30,
    maxConsecutiveDays: 0,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 4,
  },
  {
    name: 'Babalık İzni',
    code: 'PATERNITY',
    color: '#8B5CF6',
    icon: '👶',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: true,
    minDaysNotice: 7,
    maxConsecutiveDays: 0,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 5,
  },
  {
    name: 'Ücretsiz İzin',
    code: 'UNPAID',
    color: '#6B7280',
    icon: '⏸️',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: false,
    minDaysNotice: 14,
    maxConsecutiveDays: 0,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: false,
    sortOrder: 6,
  },
  {
    name: 'Evlilik İzni',
    code: 'MARRIAGE',
    color: '#F59E0B',
    icon: '💍',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: true,
    minDaysNotice: 7,
    maxConsecutiveDays: 0,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 7,
  },
  {
    name: 'Ölüm İzni',
    code: 'DEATH',
    color: '#1F2937',
    icon: '🖤',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: true,
    minDaysNotice: 1,
    maxConsecutiveDays: 0,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 8,
  },
  {
    name: 'Mazeret İzni',
    code: 'EXCUSE',
    color: '#F97316',
    icon: '📝',
    accrualMethod: 'NONE',
    defaultDaysPerYear: 0,
    requiresApproval: true,
    requiresDocument: false,
    minDaysNotice: 2,
    maxConsecutiveDays: 3,
    canCarryOver: false,
    carryOverDays: 0,
    isPaid: true,
    sortOrder: 9,
  },
];

/**
 * Kıdem yılına göre yıllık izin günü hesaplama (4857 İş Kanunu)
 * 1-5 yıl: 14 gün
 * 6-15 yıl: 20 gün
 * 16+ yıl: 26 gün
 */
export function calculateAnnualLeaveDays(kidemYili: number): number {
  if (kidemYili < 6) return 14;
  if (kidemYili < 16) return 20;
  return 26;
}